### ISSUE TITLE
cli windows exe is corrupt

### ISSUE THREAD

**Issue by chrislittle** [CenturyLinkCloud/clc-python-sdk#18]
https://github.com/CenturyLinkCloud/clc-python-sdk/blob/master/src/dist/clc-cli.exe

this is corrupt and doesn't function

**Comment by hk1232** [comment]
Verified d/l using "raw" link functions.  

![image](https://cloud.githubusercontent.com/assets/7604630/8778032/266f3cd4-2ec1-11e5-8f82-0736e51f3332.png)
