### ISSUE TITLE
Unable to retrieve new server details when server name has more than 5 chars

### ISSUE THREAD

**Issue by jcortega** [CenturyLinkCloud/clc-python-sdk#27]
I believe the <6 condition is not necessary or should be <=6 ?

https://github.com/CenturyLinkCloud/clc-python-sdk/blob/70858e3b5ff45a465f83282e20c0a6ffa2f6ba4c/src/clc/APIv2/queue.py#L55

**Comment by jbouse** [comment]
Would this (https://github.com/SterlingBackcheck/clc-python-sdk/commit/fb38d3674696eae34da16fe6ff69d26cb61b2dea) not be a better solution? As the length of the Alias would affect the possible lenght of the sever name.
