### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by computergeek125** [CenturyLinkCloud/clc-python-sdk#40]
Would it be possible to update this code base to be compatible with Python 3?

I tried installing this module via both pip and git, and received this same error.  I am running Python 3.6.1 on Cygwin and 3.5.2 on Ubuntu.
```
Traceback (most recent call last):
  File "my-file.py", line 1, in <module>
    import clc
  File "/usr/lib/python3.6/site-packages/clc_sdk-2.46-py3.6.egg/clc/__init__.py", line 19, in <module>
ModuleNotFoundError: No module named 'APIv1'
```

**Comment by ZuluPro** [comment]
Any news about Python3 support ? (just with V2)

**Comment by davisein** [comment]
@ZuluPro @computergeek125 A recent PR to support python 3 has been merged (thanks @ZuluPro for the effort!!).

I'm closing this ticket but please let me know if there is an error in our support of Python3.

**Comment by computergeek125** [comment]
I'll check this out.  Thanks all!
