### ISSUE TITLE
The create server call is not giving proper reason for failure

### ISSUE THREAD

**Issue by phanikumargvss** [CenturyLinkCloud/clc-python-sdk#6]
By debugging, it seems reason for create server failure is "Memory limit exceeded", but it is returning 
TypeError: __init__() takes at most 3 arguments (4 given) error.

(Pdb) p r
<Response [400]>
(Pdb) p r.__dict__
{'cookies': <<class 'requests.cookies.RequestsCookieJar'>[]>, '_content': '{"message":"Memory limit exceeded -> available: 2, requested: 4"}', 'headers': {'content-length': '65', 'expires': '-1', 'pragma': 'no-cache', 'cache-control': 'no-cache', 'date': 'Tue, 07 Apr 2015 21:16:23 GMT', 'content-type': 'application/json; charset=utf-8'}, 'url': u'https://api.ctl.io/v2/servers/AVNI', 'status_code': 400, '_content_consumed': True, 'encoding': 'utf-8', 'request': <PreparedRequest [POST]>, 'connection': <requests.adapters.HTTPAdapter object at 0x2447c90>, 'elapsed': datetime.timedelta(0, 8, 175386), 'raw': <requests.packages.urllib3.response.HTTPResponse object at 0x2451450>, 'reason': 'Bad Request', 'history': []}
(Pdb) c

**Comment by hk1232** [comment]
This is an error related to account resource limits not with the SDK itself.  I've just created an update that will appropriately raise the error details when this occurs in the future.
